services:
  postgres:
    build: ./postgres
    image: xakivikax/peaksdb
    restart: on-failure:3
    ports:
      - 5555:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - ci-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DB}

  backend:
    build: ./app
    image: xakivikax/peaks
    restart: no
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    container_name: peaks-container-1
    volumes:
      - ./app:/code/app
    networks:
      - ci-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DB}

    command: |
      bash -c "/code/app/entrypoint/02-start.sh"

volumes:
  postgres_data:

networks:
  ci-network:
    driver: bridge
