name: Publish docker images
on:
  pull_request:
  push:
    branches:
      - "feat/*"

jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'same-as-branch-mentioned-above'

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push peaks app
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/peaks:latest
      - name: build and push peaks db
        id: build-push-db
        uses: docker/build-push-action@v3
        with:
          context: .
          file: postgres/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/peaksdb:latest